apiVersion: v1
kind: ReplicationController
metadata:
  # Change the name
  name: deis-builder
  labels:
    heritage: deis
spec:
  replicas: 1

  # Change the selector name
  selector:
    app: deis-builder
  template:
    metadata:
      labels:
        # Important: these labels need to match the selector above
        app: deis-builder
    spec:
      containers:
<<<<<<< HEAD:manifests/deis-bpbuilder-rc.yaml
        - name: deis-bpbuilder
        image: deis/bpbuilder:2.0.0
          ports:
            - containerPort: 2222
        command:
          - entrypoint.sh  
=======
      - name: deis-builder
        image: smothiki/builder:2.4.3
        ports:
          - containerPort: 2223
          - containerPort: 3000
        env:
          - name: "EXTERNAL_PORT"
            value: "2223"
>>>>>>> ed2f114... feat(builder):couple builders and add dockerbuilder pod:manifests/deis-builder-rc.yaml
