apiVersion: v1
kind: ReplicationController
metadata:
  # Change the name
  name: deis-builder
  labels:
    heritage: deis
spec:
  replicas: 1

  # Change the selector name
  selector:
    app: deis-builder
  template:
    metadata:
      labels:
        # Important: these labels need to match the selector above
        app: deis-builder
    spec:
      containers:
      - name: deis-builder
        image: arschles/builder:2.0.0-20151124104811
        ports:
          - containerPort: 2223
          - containerPort: 3000
        env:
          - name: "EXTERNAL_PORT"
            value: "2223"
