apiVersion: v1
kind: Secret
metadata:
  name: object-store
  heritage: s3
type: Opaque
data:
  access-key-id: QUtJQUpYSE5GS0xLUkY1TVE=
  access-secret-key: UnYrQWtTa1E2OFRZUrY1ROUURMbGlnYkEzTGIwWWd4Z1I3MQ==
