# A debugging utility for testing Minio from within k8s.
apiVersion: v1
kind: Pod
metadata:
  name: repo_name
  labels:
    heritage: deis
    version: 2015-sept
spec:
  restartPolicy: Never
  containers:
    - name: repo_name
      imagePullPolicy: Always
      image: arschles/dockerbuilder:0.0.1-20151124102330
      env:
        - name: DEBUG
          value: "1"
        - name: TAR_URL
          value: tar-url
        - name: IMG_NAME
          value: imagename
        - name: ACCESS_KEY_FILE
          value: /var/run/secrets/object/store/access_key
        - name: ACCESS_SECRET_FILE
          value: /var/run/secrets/object/store/access_secret
        # - name : REG_URL
        #   value: puturl
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-socket
        - name: object-store
          mountPath: /var/run/secrets/object/store
          readOnly: true
  volumes:
    - name: object-store
      secret:
        secretName: object-store
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
